### ISSUE TITLE
Using infomas-asl in EE Environment

### ISSUE THREAD

**Issue by eduzol** [rmuller/infomas-asl#10]
Hello I wonder if this library would work in a Java EE Application Server. I am using your excellent library in a java SE environment and works great. But it doesn't detect annotations in Jboss AS 7.1

**Comment by rmuller** [comment]
Yes, i checked Jetty, Tomcat and GlassFish. These enviroments all work as expected. Just added support for WebLogic. See issue #30. Only WildFly/JBoss AS is missing currently, see issue #29
