### ISSUE TITLE
Scan jars with non .jar extensions

### ISSUE THREAD

**Issue by alebar** [rmuller/infomas-asl#23]
Hi,

My jar is uploaded to some third party software which is saving it to some temporary location. And while doing that it's changing my jar's name to something like myjarname.jar.2343252352344.tmp (or something). It is still the same file, but it's name doesn't end in ".jar" anymore.

And it's being ignored while scanning because in ClassFileIterator.java there's this line (105): `endsWithIgnoreCase(name, ".jar")`

If you'll find another way to determine is the file is a jar or not - that will be great.

**Comment by rmuller** [comment]
Finally improved this implementation as advised here: https://github.com/rmuller/infomas-asl/pull/25
