### ISSUE TITLE
Jar files not scanned if they are not 'root files'

### ISSUE THREAD

**Issue by halfmanhalffish** [rmuller/infomas-asl#26]
If I use the `detect(File[])` API (the one which doesn't look at the
classpath but instead at the files/directories specified in the parameter)
it ignores jar files that it discovers when walking
the directory tree unless the jar file was specified in the `File[]`
parameter (a 'root file') .

The code that makes this happen is
`else if (fileIterator.isRootFile() && endsWithIgnoreCase(name, ".jar"))`
in `ClassFileIterator.next()`
specifically the `isRootFile()` check.

This behaviour is not what I would have expected.  Assuming that it's
intended, a mention in the javadoc would be worthwhile.

**Comment by rmuller** [comment]
Class path should contain directories (top level directory as package root) and/or jar files (including zip files), see http://docs.oracle.com/javase/8/docs/technotes/tools/unix/classpath.html.

Good point this is missing in the documentation Thanks!
