### ISSUE TITLE
it'd be nice if report...Annotation() methods could report where they found their annotation

### ISSUE THREAD

**Issue by halfmanhalffish** [rmuller/infomas-asl#28]
This applies to 3.0.4.  Please ignore if this has been dealt with already - I haven't checked.

My code in `reportTypeAnnotation()` knows that an annotated class was found, but doesn't know in which jar or directory it was found.  It'd be nice if another parameter could be added to `reportTypeAnnotation()` to indicate it.

**Comment by rmuller** [comment]
This is possible when using version 3.1.x. Will not be added to version 3.0.x branch
