### ISSUE TITLE
Add support for discovering all interface implementations or class extensions

### ISSUE THREAD

**Issue by kaqqao** [rmuller/infomas-asl#35]
This library is quite amazing for scanning the classpath for classes of interest.
Is there a chance to perhaps extend it to allow searching based on super types, i.e. to find all classes implementing a specific interface or extending a specific class?

**Comment by rmuller** [comment]
Thanks for the nice words :)

No, this is beyond the scope of this project. But you are not the first asking for this kind of functionality. So will think about it. However, do not expect something in the near future (too busy right now with other projects)

**Comment by rmuller** [comment]
Out of scope.
